### ISSUE TITLE
Assertion failed: Assertion failed on expression: 'srcAttach < m_CurrentFramebuffer.colorCount && "We should always resolve only current RT"'

### ISSUE THREAD

**Issue by foldalma** [RELNO/CSharpScope_Volpe#4]

**Comment by RELNO** [comment]
Can you provide solving method for future reference?

Thanks,
A

**Comment by foldalma** [comment]
I was looking around for a long time & I believe it was the antialiased keystoned texture--it was not supposed to be aliased. 

It is, though, in Andorra, so this might just have come up due to the move.
